- name: Add workers
  community.general.docker_swarm:
  state: join
  advertise_addr: swarm-worker
  join_tokem: "{{hostvars['swarm-manager']['swarm_info']['swarm-facts']['JoinTokens']['Worker']"
  remote_addrs: ['swarm-manager:2377']