version: '3.7'
services:
  application:
    build: ./application
    image: rfarq/application
    deploy:
      replicas: 5
    ports:
    - published: 5000
      target: 5000
  entry_code:
    build: ./entry_code
    image: rfarq75/entry_code
    deploy:
      replicas: 5
    ports: 
    - published: 5001
      target: 5001
  letters:
    build: ./letters
    image: rfarq/letters
    deploy:
      replicas: 5
    ports:
    - published: 5002
      target: 5002
  numbers:
    build: ./numbers
    image: rfarq75/numbers
    deploy:
      replicas: 5
    ports: 
    - published: 5003
      target: 5003