version: '3.7'
services:
  service_1:
    build: ./service_1
    image: rfarq75/service_1
    deploy:
      replicas: 3
    ports:
    - published: 5000
      target: 5000
      protocol: tcp
    environment:
      DB_URI: ${DB_URI}
      KEY: ${KEY}
  service_2:
    build: ./service_2
    image: rfarq75/service_2
    deploy:
      replicas: 3
    ports: 
    - published: 5001
      target: 5001
      protocol: tcp
  service_3:
    build: ./service_3
    image: rfarq75/service_3
    deploy:
      replicas: 3
    ports: 
    - published: 5002
      target: 5002
      protocol: tcp
  service_4:
    build: ./service_4
    image: rfarq75/service_4
    deploy:
      replicas: 3
    ports: 
    - published: 5003
      target: 5003
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - published: 80
      target: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - service_1
