version: '3.7'
services:
  service_1:
    build: ./service_1
    image: rfarq/service_1
    deploy:
      replicas: 5
    ports:
    - published: 5000
      target: 5000
  service_2:
    build: ./service_2
    image: rfarq/service_2
    deploy:
      replicas: 5
    ports:
    - published: 5001
      target: 5001
  service_3:
    build: ./service_3
    image: rfarq75/service_3
    deploy:
      replicas: 5
    ports: 
    - published: 5002
      target: 5002
  service_4:
    build: ./service_4
    image: rfarq75/service_4
    deploy:
      replicas: 5
    ports: 
    - published: 5003
      target: 5003