- name: Install packages using apt
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools
  tags: docker

- name: Add Docker GPG apt Key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Run and enable docker
  service:
    name: docker
    state: started

- name: Enable python3-pip
  apt:
    name: python3-pip
    state: latest

- name: pip docker
  pip:
    executable: pip3
    name: docker
